import AddCustomer from "../Pages/Customer/AddCustomer";
import CreditCustomer from "../Pages/Customer/CreditCustomer";
import CustomerAdvance from "../Pages/Customer/CustomerAdvance";
import CustomerLedger from "../Pages/Customer/CustomerLedger";
import CustomerList from "../Pages/Customer/CustomerList";
import PaidCustomer from "../Pages/Customer/PaidCustomer";
import Dashboard from "../Pages/Dashboard/Dashboard";
import AddCategory from "../Pages/Product/AddCategory";
import AddProduct from "../Pages/Product/AddProduct";
import AddUnit from "../Pages/Product/AddUnit";
import CategoryList from "../Pages/Product/CategoryList";
import UnitList from "../Pages/Product/UnitList";
import NewSale from "../Pages/Sales/NewSale";
import AddSupplier from "../Pages/Supplier/AddSupplier";
// import AddCustomer from "../Pages/Supplier/Customer/AddCustomer";
import SupplierAdvance from "../Pages/Supplier/SupplierAdvance";
import SupplierLedger from "../Pages/Supplier/SupplierLedger";
import SupplierList from "../Pages/Supplier/SupplierList";
// import SupplierAdvance from "../Pages/Supplier/SupplierAdvance/SupplierAdvance";
// import SupplierLedger from "../Pages/Supplier/SupplierLedger/SupplierLedger";
// import SupplierList from "../Pages/Supplier/SupplierList/SupplierList";
// import AddSupplier from "../Pages/Supplier/AddSupplier";
// import SupplierList from "../Pages/Supplier/SupplierList";

export const routes = [
  {
    id: 1,
    title: "Dashboard",
    path: "/dashboard",
    icon: "menu-icon fa fa-cogs",
    component: <Dashboard />,
  },
  {
    id: 0,
    title: "Sale",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "New Sale",
        icon: "menu-icon fa fa-cogs",
        path: "/sale",
        component: <NewSale />,
      },
      {
        id: 0,
        title: "Manage Sale",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "POS Sale",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Sales Terms List",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Add Sales Terms",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Customer",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add Customer",
        icon: "menu-icon fa fa-cogs",
        path: "/add-customer",
        component: <AddCustomer />,
      },
      {
        id: 0,
        title: "Customer List",
        icon: "menu-icon fa fa-cogs",
        path: "/customer-list",
        component: <CustomerList />,
      },
      {
        id: 0,
        title: "Credit Customer",
        icon: "menu-icon fa fa-cogs",
        path: "/credit-customer",
        component: <CreditCustomer />,
      },
      {
        id: 0,
        title: "Paid Customer",
        icon: "menu-icon fa fa-cogs",
        path: "/paid-customer",
        component: <PaidCustomer />,
      },
      {
        id: 0,
        title: "Customer Ledger",
        icon: "menu-icon fa fa-cogs",
        path: "/customer-ledger",
        component: <CustomerLedger />,
      },
      {
        id: 0,
        title: "Customer Advance",
        icon: "menu-icon fa fa-cogs",
        path: "/customer-advance",
        component: <CustomerAdvance />,
      },
    ],
  },
  {
    id: 0,
    title: "Supplier",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add Supplier",
        icon: "menu-icon fa fa-cogs",
        path: "/add-supplier",
        component: <AddSupplier />,
      },
      {
        id: 0,
        title: "Supplier List",
        icon: "menu-icon fa fa-cogs",
        path: "/supplier-list",
        component: <SupplierList />,
      },
      {
        id: 0,
        title: "Supplier Ledger",
        icon: "menu-icon fa fa-cogs",
        path: "/supplier-ledger",
        component: <SupplierLedger />,
      },
      {
        id: 0,
        title: "Supplier Advance",
        icon: "menu-icon fa fa-cogs",
        path: "/supplier-advance",
        component: <SupplierAdvance />,
      },
    ],
  },
  {
    id: 0,
    title: "Product",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add Category",
        icon: "menu-icon fa fa-cogs",
        path: "/add-category",
        component: <AddCategory />,
      },
      {
        id: 0,
        title: "Category List",
        icon: "menu-icon fa fa-cogs",
        path: "/category-list",
        component: <CategoryList />,
      },
      {
        id: 0,
        title: "Add Unit",
        icon: "menu-icon fa fa-cogs",
        path: "/add-unit",
        component: <AddUnit />,
      },
      {
        id: 0,
        title: "Unit List",
        icon: "menu-icon fa fa-cogs",
        path: "/unit-list",
        component: <UnitList />,
      },
      {
        id: 0,
        title: "Add Product",
        icon: "menu-icon fa fa-cogs",
        path: "/add-product",
        component: <AddProduct />,
      },
      {
        id: 0,
        title: "Add Product (CSV)",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Manage Product",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Purchase",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add Purchase",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Manage Purchase",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Stock",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Stock Report",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Accounts",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Chart of Accounts",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Opening Balance",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Add Payment Method",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Payment Method List",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Supplier Payment",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Customer Receive",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Service Payment",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Cash Adjustment",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Debit Voucher",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Credit Voucher",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Contra Voucher",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Journal Voucher",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Voucher Approval",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Report",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Closing",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Closing Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Todays Customer Receipt",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Sales Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "User Wise Sales Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Due Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Shipping Cost Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Purchase Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Purchase Report (Category wise)",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Sales Report (Product Wise)",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Sales Report (Category wise)",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Sales Return",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Supplier Return",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "TAX Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Profit Report (Sale Wise)",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Human Resources",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "HRM",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Attendance",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Payroll",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Expense",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Office Loan",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Personal Loan",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Bank",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add New Bank",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Manage Bank",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Bank Transaction",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Bank Ledger",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Services",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add Service",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Manage Service",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Service Invoice",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Manage Service Invoice",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Quotation",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Add Quotation",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Manage Quotation",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "TAX",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "VAT & TAX Settings",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "TAX Settings",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Add Income Tax",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Manage Income Tax",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Tax Report",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Tax Report (Invoice Wise)",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Return",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Return",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Stock Return List",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Supplier Return List",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Wastage Return List",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Settings",
    icon: "menu-icon fa fa-cogs",
    data: [
      {
        id: 0,
        title: "Software Settings",
        icon: "menu-icon fa fa-cogs",
        path: "",
        component: "",
      },
      {
        id: 0,
        title: "Role Permission",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "SMS",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Data Synchronizer",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
      {
        id: 0,
        title: "Update Now",
        icon: "menu-icon fa fa-cogs",
        path: "/",
        component: "",
      },
    ],
  },
  {
    id: 0,
    title: "Addons",
    icon: "menu-icon fa fa-cogs",
  },
];
