export const data = [
  {
    head_name: "Assets",
    id: 1,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 0,
  },
  {
    head_name: "Equity",
    id: 2,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 0,
  },
  {
    head_name: "Expenses",
    id: 3,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 0,
  },
  {
    head_name: "Liabilities",
    id: 4,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 0,
  },
  {
    head_name: "Revenues",
    id: 5,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 0,
  },
  {
    head_name: "Current Assets",
    id: 6,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 1,
  },
  {
    head_name: "Fixed Assets",
    id: 7,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 1,
  },
  {
    head_name: "Non-Current Assets",
    id: 8,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 1,
  },
  {
    head_name: "Account Receivable",
    id: 9,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 6,
  },
  {
    head_name: "Cash In Banks",
    id: 10,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 6,
  },
  {
    head_name: "Cash In Boxes",
    id: 11,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 6,
  },
  {
    head_name: "Inventory Accounts",
    id: 12,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 6,
  },
  {
    head_name: "Customers",
    id: 13,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 9,
  },
  {
    head_name: "Loan Receivables",
    id: 14,
    opening_balance: 50000,
    balance: 150000,
    parent_id: 9,
  },
  {
    head_name: "Jack",
    id: 15,
    opening_balance: 0,
    balance: 0,
    parent_id: 13,
  },
  {
    head_name: "Bank",
    id: 16,
    opening_balance: 0,
    balance: 0,
    parent_id: 11,
  },
  {
    head_name: "Cash In Hand",
    id: 17,
    opening_balance: 0,
    balance: 0,
    parent_id: 11,
  },
  {
    head_name: "Inventory",
    id: 18,
    opening_balance: 0,
    balance: 0,
    parent_id: 12,
  },
  {
    head_name: "Service Receive",
    id: 19,
    opening_balance: 0,
    balance: 0,
    parent_id: 8,
  },
  {
    head_name: "Customer Service-2",
    id: 20,
    opening_balance: 0,
    balance: 0,
    parent_id: 19,
  },
  {
    head_name: "Customer Service-3",
    id: 21,
    opening_balance: 0,
    balance: 0,
    parent_id: 19,
  },
  {
    head_name: "Home Delivery-1",
    id: 22,
    opening_balance: 0,
    balance: 0,
    parent_id: 19,
  },
  {
    head_name: "Direct Expenses",
    id: 23,
    opening_balance: 0,
    balance: 0,
    parent_id: 3,
  },
  {
    head_name: "Indirect Expenses",
    id: 24,
    opening_balance: 0,
    balance: 0,
    parent_id: 3,
  },
  {
    head_name: "General and administrative expenses",
    id: 25,
    opening_balance: 0,
    balance: 0,
    parent_id: 24,
  },
  {
    head_name: "Expenses of public utilities and services",
    id: 26,
    opening_balance: 0,
    balance: 0,
    parent_id: 25,
  },
  {
    head_name: "Payroll",
    id: 27,
    opening_balance: 0,
    balance: 0,
    parent_id: 25,
  },
  {
    head_name: "Basic Salary",
    id: 28,
    opening_balance: 0,
    balance: 0,
    parent_id: 27,
  },
  {
    head_name: "Employee Salary",
    id: 29,
    opening_balance: 0,
    balance: 0,
    parent_id: 27,
  },
  {
    head_name: "Current Liabilities",
    id: 30,
    opening_balance: 0,
    balance: 0,
    parent_id: 4,
  },
  {
    head_name: "Non-Current Liabilities",
    id: 31,
    opening_balance: 0,
    balance: 0,
    parent_id: 4,
  },
  {
    head_name: "Accounts Payable",
    id: 32,
    opening_balance: 0,
    balance: 0,
    parent_id: 30,
  },
  {
    head_name: "Employee Ledger",
    id: 33,
    opening_balance: 0,
    balance: 0,
    parent_id: 32,
  },
  {
    head_name: "Suppliers",
    id: 34,
    opening_balance: 0,
    balance: 0,
    parent_id: 32,
  },
  {
    head_name: "Value added tax",
    id: 35,
    opening_balance: 0,
    balance: 0,
    parent_id: 32,
  },
  {
    head_name: "Jane White",
    id: 36,
    opening_balance: 0,
    balance: 0,
    parent_id: 33,
  },
  {
    head_name: "Hudson",
    id: 37,
    opening_balance: 0,
    balance: 0,
    parent_id: 34,
  },
  {
    head_name: "Other revenue",
    id: 38,
    opening_balance: 0,
    balance: 0,
    parent_id: 5,
  },
  {
    head_name: "Sales revenue",
    id: 39,
    opening_balance: 0,
    balance: 0,
    parent_id: 5,
  },
  {
    head_name: "Discount Received",
    id: 40,
    opening_balance: 0,
    balance: 0,
    parent_id: 38,
  },
  {
    head_name: "Sales",
    id: 41,
    opening_balance: 0,
    balance: 0,
    parent_id: 39,
  },
  {
    head_name: "Product sales",
    id: 42,
    opening_balance: 0,
    balance: 0,
    parent_id: 41,
  },
  {
    head_name: "Service sales",
    id: 43,
    opening_balance: 0,
    balance: 0,
    parent_id: 41,
  },
];
