import React from "react";
import { useTranslation } from "react-i18next";
import ManageSalaryTable from "./ManageSalaryTable";

function ManageSalaryGenerate() {
  const { t } = useTranslation();

  const columns = [
    {
      field: "sl",
      caption: t("SL"),
      allowEditing: false,
    },
    {
      field: "salary_month",
      caption: t("Salary Month"),
      allowEditing: false,
    },
    {
      field: "generated_by",
      caption: t("Generated By"),
      allowEditing: false,
    },
    {
      field: "action",
      caption: t("Action"),
      allowEditing: false,
    },
  ];

  return <ManageSalaryTable columns={columns} title="Salary Payment" />;
}

export default ManageSalaryGenerate;
